language: julia

sudo: required
dist: trusty

os:
    - linux

julia:
    - 0.4.0
    - 0.4.1
    - 0.4.2
    - 0.4.3
    - nightly

matrix:
    allow_failures:
        - julia: nightly

before_install:
    - sudo apt-get update
    - sudo apt-get install libmpich2-dev mpich2 hdf5-tools libhdf5-dev -y
    - sudo apt-get install libopenblas-dev -y


script:
    - julia -e 'Pkg.clone(pwd());'
    - julia -e 'Pkg.checkout("ParallelAccelerator")'
    - CXX=mpic++ LATTE_BUILD_MPI=1 OPENBLAS_LIB=libopenblas.so julia -e 'Pkg.build("Latte")'
    - julia --code-coverage=user test/runtests.jl

after_success:
    - julia bin/coverage.jl

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0dbc11ae0ac8815398b3
        on_success: change
        on_failure: always
        on_start: never
