language: julia

dist: trusty

os:
    - linux

julia:
    - 0.4.0
    - 0.4.1
    - 0.4.2
    - 0.4.3
    - nightly

matrix:
    allow_failures:
        - julia: nightly

script: 
    - julia -e 'Pkg.clone(pwd());'
    - julia -e 'Pkg.build("Latte")'
    - julia --code-coverage=user test/runtests.jl

after_success:
    - julia -e 'cd(Pkg.dir("Latte")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0dbc11ae0ac8815398b3
        on_success: change
        on_failure: always
        on_start: never
