language: julia

sudo: required
dist: trusty

os:
    - linux

julia:
    - 0.4

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.9 g++-4.9
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
    - sudo apt-get install libmpich2-dev mpich2 hdf5-tools libhdf5-mpich2-dev -y
    - sudo apt-get install libopenblas-dev -y

before_script:
      - export PATH=$HOME/.local/bin:$PATH

script:
    - julia -e 'Pkg.clone(pwd());'
    - julia -e 'Pkg.checkout("ParallelAccelerator")'
    - julia -e 'Pkg.checkout("CompilerTools")'
    - CXX=mpic++ LATTE_BUILD_MPI=1 OPENBLAS_LIB=libopenblas.so julia -e 'Pkg.build("Latte")'
    - cd test
    - julia --code-coverage=user runtests.jl
    - cd ..

after_success:
    - julia bin/coverage.jl
    - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
    - julia -e 'cd(Pkg.dir("Latte")); include(joinpath("docs", "make.jl"))'

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0dbc11ae0ac8815398b3
        on_success: change
        on_failure: always
        on_start: never
