site_name: Latte.jl
repo_url:  https://github.com/IntelLabs/Latte.jl
site_description: A high-performance DSL for deep neural networks.
site_author: Intel Labs

theme: readthedocs

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - tables
    - fenced_code

docs_dir: 'build'

pages:
    - Home: index.md

